import { makeStyles } from '@material-ui/core';
import {
  blackColor,
  boxShadow,
  container,
  dangerColor,
  defaultBoxShadow,
  drawerWidth,
  grayColor,
  hexToRgb,
  infoColor,
  successColor,
  transition,
  warningColor,
  whiteColor,
} from 'styles/common';

export const landingPageNavBarStyles = makeStyles((theme) => ({
  appBar: {
    backgroundColor: 'transparent',
    boxShadow: 'none',
    borderBottom: 0,
    marginBottom: 0,
    position: 'absolute',
    width: '100%',
    paddingTop: 10,
    zIndex: 1029,
    color: grayColor[6],
    border: 0,
    borderRadius: 3,
    padding: '10px 0',
    transition: 'all 150ms ease 0s',
    minHeight: 50,
    display: 'block',
  },
  container: {
    ...container,
    minHeight: 50,
  },
  flex: {
    flex: 1,
  },
  title: {
    lineHeight: '30px',
    fontSize: 18,
    borderRadius: 3,
    textTransform: 'uppercase',
    color: whiteColor,
    letterSpacing: 'unset',
    '&:hover,&:focus': {
      background: 'transparent',
      color: whiteColor,
    },
  },
  appResponsive: {
    top: 8,
  },
  primary: {
    backgroundColor: theme.palette.primary.main,
    color: whiteColor,
    ...defaultBoxShadow,
  },
  secondary: {
    backgroundColor: theme.palette.secondary.main,
    color: whiteColor,
    ...defaultBoxShadow,
  },
  info: {
    backgroundColor: infoColor[0],
    color: whiteColor,
    ...defaultBoxShadow,
  },
  success: {
    backgroundColor: successColor[0],
    color: whiteColor,
    ...defaultBoxShadow,
  },
  warning: {
    backgroundColor: warningColor[0],
    color: whiteColor,
    ...defaultBoxShadow,
  },
  danger: {
    backgroundColor: dangerColor[0],
    color: whiteColor,
    ...defaultBoxShadow,
  },
  list: {
    fontSize: 14,
    margin: 0,
    marginRight: -15,
    paddingLeft: 0,
    listStyle: 'none',
    color: whiteColor,
    paddingTop: 0,
    paddingBottom: 0,
  },
  listItem: {
    float: 'left',
    position: 'relative',
    display: 'block',
    width: 'auto',
    margin: 0,
    padding: 0,
    [theme.breakpoints.down('sm')]: {
      zIndex: 999,
      width: '100%',
      paddingRight: 15,
    },
  },
  navLink: {
    color: whiteColor,
    margin: '0 5px',
    paddingTop: 15,
    paddingBottom: 15,
    fontWeight: 500,
    fontSize: 12,
    textTransform: 'uppercase',
    borderRadius: 3,
    lineHeight: '20px',
    position: 'relative',
    display: 'block',
    padding: '10px 15px',
    textDecoration: 'none',
    '&:hover,&:focus': {
      color: whiteColor,
      background: `rgba(${hexToRgb(grayColor[17])}, 0.2)`,
    },
  },
  listItemIcon: {
    marginTop: -3,
    top: 0,
    position: 'relative',
    marginRight: 3,
    width: 20,
    height: 20,
    verticalAlign: 'middle',
    color: 'inherit',
    display: 'inline-block',
  },
  listItemText: {
    flex: 'none',
    padding: 0,
    minWidth: 0,
    margin: 0,
    display: 'inline-block',
    position: 'relative',
    whiteSpace: 'nowrap',
  },
  navLinkActive: {
    backgroundColor: `rgba(${hexToRgb(whiteColor)}, 0.1)`,
  },
  drawerPaper: {
    border: 'none',
    bottom: 0,
    transitionProperty: 'top,bottom,width',
    transitionDuration: '0.2s,0.2s,0.35s',
    transitionTimingFunction: 'linear,linear,ease',
    ...boxShadow,
    width: drawerWidth,
    ...boxShadow,
    position: 'fixed',
    display: 'block',
    top: 0,
    height: '100vh',
    right: 0,
    left: 'auto',
    visibility: 'visible',
    overflowY: 'visible',
    borderTop: 'none',
    textAlign: 'left',
    paddingRight: 0,
    paddingLeft: 0,
    ...transition,
    '&:before,&:after': {
      position: 'absolute',
      zIndex: 3,
      width: '100%',
      height: '100%',
      content: '""',
      display: 'block',
      top: 0,
    },
    '&:after': {
      background: blackColor,
      opacity: 0.8,
    },
  },
  sidebarButton: {
    '&,&:hover,&:focus': {
      color: whiteColor,
    },
    top: -2,
  },
}));
