env:
  es6: true
  node: true
  browser: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:prettier/recommended"
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - prettier
